---
apiVersion: v1
kind: Namespace
metadata:
    name: nirmata-opencost
---
# Source: prometheus/templates/node-exporter/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: "node-exporter"
    app: prometheus
    release: nirmata-opencost
    chart: prometheus-15.12.2
    heritage: Helm
  name: nirmata-opencost-prometheus-node-exporter
  namespace: nirmata-opencost
spec:
  selector:
    matchLabels:
      component: "node-exporter"
      app: prometheus
      release: nirmata-opencost
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: "node-exporter"
        app: prometheus
        release: nirmata-opencost
        chart: prometheus-15.12.2
        heritage: Helm
    spec:
      serviceAccountName: nirmata-opencost-prometheus-node-exporter
      containers:
        - name: prometheus-node-exporter
          image: "quay.io/prometheus/node-exporter:v1.3.1"
          imagePullPolicy: "IfNotPresent"
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            - --web.listen-address=:9100
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
          resources:
            {}
          securityContext:
            allowPrivilegeEscalation: false          
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root
              mountPath: /host/root
              mountPropagation: HostToContainer
              readOnly: true
      hostNetwork: true
      hostPID: true
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
---
# Source: prometheus/templates/node-exporter/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "node-exporter"
    app: prometheus
    release: nirmata-opencost
    chart: prometheus-15.12.2
    heritage: Helm
  name: nirmata-opencost-prometheus-node-exporter
  namespace: nirmata-opencost
  annotations:
    {}
---
# Source: prometheus/templates/node-exporter/svc.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    component: "node-exporter"
    app: prometheus
    release: nirmata-opencost
    chart: prometheus-15.12.2
    heritage: Helm
  name: nirmata-opencost-prometheus-node-exporter
  namespace: nirmata-opencost
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    component: "node-exporter"
    app: prometheus
    release: nirmata-opencost
  type: "ClusterIP"
